/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package notiz.app.test;

import notiz.app.test.DatabaseConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Moritz
 */
public class GUI extends javax.swing.JFrame {
    
    
        private DatabaseConnection konnektor;

    /**
     * Creates new form GUI
     */
    public GUI() {
        try {
            initComponents();

            this.konnektor = new DatabaseConnection("localhost", "notizapp", "root", "");
            this.konnektor.open();


        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Fehler! Verbindung konnte nicht aufgebaut werden: " + ex);
        }
    }
    boolean print = true;

    ArrayList<String> ordnerNamen = new ArrayList();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PKadd = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        PKaddBtnAdd = new javax.swing.JButton();
        PKaddTf = new javax.swing.JTextField();
        PKaddBtnCancel = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        scOrdner = new javax.swing.JScrollPane();
        lOrdner = new javax.swing.JList<>();
        spNotizen = new javax.swing.JScrollPane();
        lNotizen = new javax.swing.JList<>();
        btnopenPKadd = new javax.swing.JButton();
        btnRemoveOrdner = new javax.swing.JButton();

        PKadd.setAlwaysOnTop(true);
        PKadd.setLocation(new java.awt.Point(100, 100));
        PKadd.setSize(new java.awt.Dimension(400, 300));

        jLabel1.setText("kategorie");

        PKaddBtnAdd.setText("add");
        PKaddBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PKaddBtnAddActionPerformed(evt);
            }
        });

        PKaddTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PKaddTfActionPerformed(evt);
            }
        });

        PKaddBtnCancel.setText("cancel");
        PKaddBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PKaddBtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PKaddLayout = new javax.swing.GroupLayout(PKadd.getContentPane());
        PKadd.getContentPane().setLayout(PKaddLayout);
        PKaddLayout.setHorizontalGroup(
            PKaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PKaddLayout.createSequentialGroup()
                .addGroup(PKaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PKaddLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(PKaddLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(PKaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PKaddLayout.createSequentialGroup()
                                .addComponent(PKaddBtnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PKaddBtnCancel))
                            .addComponent(PKaddTf, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        PKaddLayout.setVerticalGroup(
            PKaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PKaddLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(PKaddTf, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PKaddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PKaddBtnAdd)
                    .addComponent(PKaddBtnCancel))
                .addGap(78, 78, 78))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setVisible(false);
        jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1InternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lOrdner.setModel(new DefaultListModel<String>());
        lOrdner.setToolTipText("");
        lOrdner.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lOrdnerValueChanged(evt);
            }
        });
        scOrdner.setViewportView(lOrdner);

        lNotizen.setModel(new DefaultListModel<String>());
        spNotizen.setViewportView(lNotizen);

        btnopenPKadd.setText("add");
        btnopenPKadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenPKaddActionPerformed(evt);
            }
        });

        btnRemoveOrdner.setText("remove");
        btnRemoveOrdner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOrdnerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scOrdner, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spNotizen, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnopenPKadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveOrdner)))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spNotizen, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scOrdner, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnopenPKadd)
                    .addComponent(btnRemoveOrdner))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnopenPKaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenPKaddActionPerformed
        PKadd.show();
    }//GEN-LAST:event_btnopenPKaddActionPerformed

    private void btnRemoveOrdnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrdnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveOrdnerActionPerformed

    private void PKaddBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PKaddBtnAddActionPerformed
        String neuerOrdner = PKaddTf.getText().trim();
        System.out.println(neuerOrdner);
        ordnerNamen.add(neuerOrdner);
        DefaultListModel<String> model = (DefaultListModel<String>) lOrdner.getModel();
        model.addElement(neuerOrdner);
        PKaddTf.setText("");
    }//GEN-LAST:event_PKaddBtnAddActionPerformed

    private void PKaddBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PKaddBtnCancelActionPerformed
        PKaddTf.setText("");
        PKadd.hide();
    }//GEN-LAST:event_PKaddBtnCancelActionPerformed

    private void lOrdnerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lOrdnerValueChanged
        if(print == true){
            String selectedValue = lOrdner.getSelectedValue();
            // Führen Sie die gewünschte Aktion aus
            System.out.println("Ausgewählter Eintrag: " + selectedValue);
            
            DefaultListModel<String> notizenListe = (DefaultListModel<String>) lNotizen.getModel();
            notizenListe.addElement("Eintrag 1");
            notizenListe.addElement("Eintrag 2");
            notizenListe.addElement("Eintrag 3");
        }
        print =! print;

        /*

        // Fügen Sie Elemente hinzu
        */
    }//GEN-LAST:event_lOrdnerValueChanged

    private void jInternalFrame1InternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1InternalFrameClosing

    }//GEN-LAST:event_jInternalFrame1InternalFrameClosing

    private void PKaddTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PKaddTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PKaddTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog PKadd;
    private javax.swing.JButton PKaddBtnAdd;
    private javax.swing.JButton PKaddBtnCancel;
    private javax.swing.JTextField PKaddTf;
    private javax.swing.JButton btnRemoveOrdner;
    private javax.swing.JButton btnopenPKadd;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> lNotizen;
    private javax.swing.JList<String> lOrdner;
    private javax.swing.JScrollPane scOrdner;
    private javax.swing.JScrollPane spNotizen;
    // End of variables declaration//GEN-END:variables
}
