 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package notiz.app.test;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.net.URL;
/**
 *
 * @author Moritz
 */
public class login extends javax.swing.JFrame {
    
    /**
     * Creates new form login
     */
    
    private DatabaseConnection konnektor;
    public static user currentuser;
    public ResultSet result;
    
    /**
    private boolean checkPasswordMatch(){        
        String password1 = new String(pwfPW.getPassword());
        String password2 = new String(pwfPWconfirm.getPassword());
        if (password1.equals(password2)) {
            return true;
        } else {
            return false;
        }
    }
    */  
    
    public void clear(){
        pwField.setText(null);
        pwfPW.setText(null);
        pwfPWconfirm.setText(null);
        tfName.setText(null);
        tfUsername.setText(null);
        userTf.setText(null);
        showPasswordChk1.setSelected(false);
        showPasswordChk.setSelected(false);
    }
    
    public void update(){
        
        String pwvm = valPW(pwfPW.getPassword(),pwfPWconfirm.getPassword());
        LStatus.setText(pwvm);
        if(!valUser(tfUsername.getText())){
            LStatus.setText("username must not be blank");
        }
    }
    
    public static boolean valUser(String username) {
        return username != null && !username.trim().isEmpty();
    }
    
    public String valPW(char[] password, char[] confirmPassword){
        String passwordStr = new String(password);
        String confirmPasswordStr = new String(confirmPassword);
        
        if (!passwordStr.equals(confirmPasswordStr)) {
            return "The passwords do not match";
        }
        
        if (passwordStr.length() < 8) {
            return "The password must be at least 8 characters long";
        }
        
        boolean hasLetter = false;
        boolean hasDigit = false;
        
        for (char ch : password) {
            if (Character.isLetter(ch)) {
                hasLetter = true;
            }
            if (Character.isDigit(ch)) {
                hasDigit = true;
            }
        }

        if (!hasLetter) {
            return "The password must contain at least one letter";
        }

        if (!hasDigit) {
            return "The password must contain at least one number";
        }

        return "The password is valid";
    }
    
    public login() {
        try {
            initComponents();
            
            this.konnektor = new DatabaseConnection("localhost", "notizapp", "root", "");
            this.konnektor.open();

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error! Connection could not be established: " + ex);
        }
    }
    
    public boolean getUser(String user){
        try {
            ResultSet ergebnis = this.konnektor.fuehreAbfrageAus("SELECT Benutzername, Anzeigename, Password FROM user WHERE Benutzername = '"+ user+ "' AND Password = '"+ pwField.getText() + "'");
            if(ergebnis.next()) {
                currentuser = new user(ergebnis.getString("Benutzername"), ergebnis.getString("Anzeigename"), ergebnis.getString("Password"));
                System.out.println(currentuser);
                System.out.println(currentuser.getName());
                System.out.println(currentuser.getUsername());
                return true;
            }
        

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error during database query:" + ex);
            
        }
        return false;
    }
    
    public static user uebergebeuser(){
        return currentuser;
    }
    
    public boolean checkUser(String username){
        
        try {
            result = this.konnektor.fuehreAbfrageAus("SELECT Benutzername, Anzeigename, Password FROM user WHERE Benutzername = '"+ username+ "'");
            if(result.next()) { 
                if(result.getString("Benutzername").equals(username)){
                    return true;
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error during database query:" + ex);    
        }
        return false;
    }
       

    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PCreateAccount = new javax.swing.JDialog();
        panel1 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Lpw = new javax.swing.JLabel();
        Lconfirmpw = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        pwfPW = new javax.swing.JPasswordField();
        pwfPWconfirm = new javax.swing.JPasswordField();
        btnPCAconfirm = new javax.swing.JButton();
        btnPCAcancel = new javax.swing.JButton();
        LStatus = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        showPasswordChk1 = new javax.swing.JCheckBox();
        PCreateAccountUser = new javax.swing.JDialog();
        panel2 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        btnCreateAccountUserOK = new javax.swing.JButton();
        PCreateAccountUserC = new javax.swing.JDialog();
        panel3 = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();
        btnCreateAccountUserOK1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        userTf = new javax.swing.JTextField();
        pwField = new javax.swing.JPasswordField();
        showPasswordChk = new javax.swing.JCheckBox();
        loginBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 2), new java.awt.Dimension(0, 2), new java.awt.Dimension(32767, 2));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        PCreateAccount.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        PCreateAccount.setTitle("JJM NOTE CREAT ACCOUNT");
        PCreateAccount.setAlwaysOnTop(true);
        PCreateAccount.setFocusCycleRoot(false);
        PCreateAccount.setIconImage(new ImageIcon(getClass().getResource("/notiz/app/test/source/icon.png")).getImage());
        PCreateAccount.setLocation(new java.awt.Point(0, 0));
        PCreateAccount.setModal(true);
        PCreateAccount.setName("CREATE A NEW ACCOUNT"); // NOI18N
        PCreateAccount.setResizable(false);
        PCreateAccount.setSize(new java.awt.Dimension(420, 324));
        PCreateAccount.setType(java.awt.Window.Type.POPUP);

        panel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("name");

        tfName.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("username");

        Lpw.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lpw.setText("password");

        Lconfirmpw.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lconfirmpw.setText("confirm password");

        tfUsername.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        tfUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfUsername.setMinimumSize(new java.awt.Dimension(64, 20));
        tfUsername.setPreferredSize(new java.awt.Dimension(64, 20));
        tfUsername.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfUsernameCaretUpdate(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        pwfPW.setToolTipText("");
        pwfPW.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        pwfPW.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pwfPWCaretUpdate(evt);
            }
        });
        pwfPW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwfPWFocusLost(evt);
            }
        });
        pwfPW.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                pwfPWInputMethodTextChanged(evt);
            }
        });
        pwfPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwfPWActionPerformed(evt);
            }
        });

        pwfPWconfirm.setToolTipText("");
        pwfPWconfirm.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        pwfPWconfirm.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pwfPWconfirmCaretUpdate(evt);
            }
        });
        pwfPWconfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwfPWconfirmFocusLost(evt);
            }
        });

        btnPCAconfirm.setBackground(java.awt.Color.lightGray);
        btnPCAconfirm.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPCAconfirm.setForeground(java.awt.Color.white);
        btnPCAconfirm.setText("confirm");
        btnPCAconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPCAconfirmActionPerformed(evt);
            }
        });

        btnPCAcancel.setBackground(java.awt.Color.lightGray);
        btnPCAcancel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPCAcancel.setForeground(java.awt.Color.white);
        btnPCAcancel.setText("cancel");
        btnPCAcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPCAcancelActionPerformed(evt);
            }
        });

        LStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel8.setText("CREATE ACCOUNT");
        jLabel8.setToolTipText("");

        showPasswordChk1.setBackground(new java.awt.Color(204, 204, 204));
        showPasswordChk1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        showPasswordChk1.setText("show Password");
        showPasswordChk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordChk1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(80, 80, 80))
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lconfirmpw)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(Lpw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnPCAconfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(btnPCAcancel))
                    .addComponent(pwfPW)
                    .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfName)
                    .addComponent(pwfPWconfirm)
                    .addComponent(showPasswordChk1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lpw)
                    .addComponent(pwfPW, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lconfirmpw)
                    .addComponent(pwfPWconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(showPasswordChk1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPCAcancel)
                    .addComponent(btnPCAconfirm))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout PCreateAccountLayout = new javax.swing.GroupLayout(PCreateAccount.getContentPane());
        PCreateAccount.getContentPane().setLayout(PCreateAccountLayout);
        PCreateAccountLayout.setHorizontalGroup(
            PCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PCreateAccountLayout.setVerticalGroup(
            PCreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PCreateAccount.getAccessibleContext().setAccessibleName("JJM NOTE CREATE ACCOUNT");
        PCreateAccount.getAccessibleContext().setAccessibleParent(this);
        PCreateAccount.setLocationRelativeTo(jPanel1);

        PCreateAccountUser.setIconImage(new ImageIcon(getClass().getResource("/notiz/app/test/source/icon.png")).getImage());
        PCreateAccountUser.setModal(true);

        panel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("this username is already taken");

        btnCreateAccountUserOK.setBackground(java.awt.Color.lightGray);
        btnCreateAccountUserOK.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateAccountUserOK.setForeground(java.awt.Color.white);
        btnCreateAccountUserOK.setText("OK");
        btnCreateAccountUserOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountUserOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnCreateAccountUserOK)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(btnCreateAccountUserOK)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PCreateAccountUserLayout = new javax.swing.GroupLayout(PCreateAccountUser.getContentPane());
        PCreateAccountUser.getContentPane().setLayout(PCreateAccountUserLayout);
        PCreateAccountUserLayout.setHorizontalGroup(
            PCreateAccountUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PCreateAccountUserLayout.setVerticalGroup(
            PCreateAccountUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PCreateAccountUser.getAccessibleContext().setAccessibleName("USERNAME TAKEN");

        PCreateAccountUserC.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        PCreateAccountUserC.setAlwaysOnTop(true);
        PCreateAccountUserC.setMinimumSize(new java.awt.Dimension(210, 120));
        PCreateAccountUserC.setModal(true);
        PCreateAccountUserC.setPreferredSize(new java.awt.Dimension(210, 100));
        PCreateAccountUserC.setResizable(false);
        PCreateAccountUserC.setSize(new java.awt.Dimension(210, 120));
        PCreateAccountUserC.setType(java.awt.Window.Type.POPUP);
        PCreateAccountUserC.setLocationRelativeTo(PCreateAccount);

        panel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Account successfully created");

        btnCreateAccountUserOK1.setBackground(java.awt.Color.lightGray);
        btnCreateAccountUserOK1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateAccountUserOK1.setForeground(java.awt.Color.white);
        btnCreateAccountUserOK1.setText("OK");
        btnCreateAccountUserOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountUserOK1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(btnCreateAccountUserOK1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnCreateAccountUserOK1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        PCreateAccountUserC.setIconImage(new ImageIcon(getClass().getResource("/notiz/app/test/source/icon.png")).getImage());

        javax.swing.GroupLayout PCreateAccountUserCLayout = new javax.swing.GroupLayout(PCreateAccountUserC.getContentPane());
        PCreateAccountUserC.getContentPane().setLayout(PCreateAccountUserCLayout);
        PCreateAccountUserCLayout.setHorizontalGroup(
            PCreateAccountUserCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PCreateAccountUserCLayout.setVerticalGroup(
            PCreateAccountUserCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PCreateAccountUserC.getAccessibleContext().setAccessibleName("ACCOUNT CREATED");
        PCreateAccountUserC.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JMM NOTE LOGIN");
        setIconImage(new ImageIcon(getClass().getResource("/notiz/app/test/source/icon.png")).getImage());
        setLocation(new java.awt.Point(800, 400));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        userTf.setToolTipText("username");
        userTf.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));

        pwField.setToolTipText("password");
        pwField.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        pwField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwFieldActionPerformed(evt);
            }
        });

        showPasswordChk.setBackground(new java.awt.Color(204, 204, 204));
        showPasswordChk.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        showPasswordChk.setText("show Password");
        showPasswordChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordChkActionPerformed(evt);
            }
        });

        loginBtn.setBackground(java.awt.Color.lightGray);
        loginBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loginBtn.setForeground(java.awt.Color.white);
        loginBtn.setText("login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(java.awt.Color.lightGray);
        cancelBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cancelBtn.setForeground(java.awt.Color.white);
        cancelBtn.setText("cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabel5.setText("JMM NOTE");

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("create account");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, javax.swing.UIManager.getDefaults().getColor("Button.borderColor"), javax.swing.UIManager.getDefaults().getColor("Button.borderColor"), javax.swing.UIManager.getDefaults().getColor("Button.borderColor"), javax.swing.UIManager.getDefaults().getColor("Button.borderColor")));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel6.setBackground(java.awt.Color.lightGray);
        jLabel6.setForeground(java.awt.Color.lightGray);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notiz/app/test/source/icon4.png"))); // NOI18N
        jLabel6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/notiz/app/test/source/icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(55, 55, 55)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userTf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cancelBtn))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1))
                            .addComponent(showPasswordChk))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPasswordChk))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(cancelBtn)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30))
        );

        pwField.getAccessibleContext().setAccessibleName("");
        loginBtn.getAccessibleContext().setAccessibleDescription("login");
        cancelBtn.getAccessibleContext().setAccessibleDescription("cancel");
        jLabel1.getAccessibleContext().setAccessibleDescription("create a new account");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleParent(PCreateAccount);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPasswordChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordChkActionPerformed
        if(showPasswordChk.isSelected()){
            pwField.setEchoChar('\u0000');
        }
        else if (!showPasswordChk.isSelected()){
            pwField.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_showPasswordChkActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        if (getUser(userTf.getText())){
            GUI gui = new GUI();
            gui.setVisible(true);
            dispose();            
        }

        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        PCreateAccount.show();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tfUsernameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfUsernameCaretUpdate
        update();
    }//GEN-LAST:event_tfUsernameCaretUpdate

    private void pwfPWconfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfPWconfirmFocusLost

    }//GEN-LAST:event_pwfPWconfirmFocusLost

    private void pwfPWconfirmCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pwfPWconfirmCaretUpdate
        update();
    }//GEN-LAST:event_pwfPWconfirmCaretUpdate

    private void btnPCAcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPCAcancelActionPerformed
        PCreateAccount.dispose();
    }//GEN-LAST:event_btnPCAcancelActionPerformed

    private void btnPCAconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPCAconfirmActionPerformed
        String pwvm = valPW(pwfPW.getPassword(),pwfPWconfirm.getPassword());
        String username = tfUsername.getText();
        if(pwvm.equals("The password is valid") && valUser(username)){
            if(checkUser(tfUsername.getText())){
                update();
            }
            else{
                try{
                    int ergebnis = this.konnektor.fuehreUpdateAus("INSERT INTO `user` (`Benutzername`, `Password`, `Anzeigename`) VALUES ('"+tfUsername.getText()+"', '"+pwfPW.getText()+"', '"+tfName.getText()+"');");
                    System.out.println(ergebnis);
                    PCreateAccountUserC.show();
                    //PCreateAccount.dispose();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error during database query:" + ex);
                }
            }

        }
        else{

        }

        //push username and password to database
    }//GEN-LAST:event_btnPCAconfirmActionPerformed

    private void pwfPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwfPWActionPerformed

    }//GEN-LAST:event_pwfPWActionPerformed

    private void pwfPWInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_pwfPWInputMethodTextChanged

    }//GEN-LAST:event_pwfPWInputMethodTextChanged

    private void pwfPWFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfPWFocusLost

    }//GEN-LAST:event_pwfPWFocusLost

    private void pwfPWCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pwfPWCaretUpdate
        update();
    }//GEN-LAST:event_pwfPWCaretUpdate

    private void btnCreateAccountUserOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountUserOKActionPerformed
        PCreateAccountUser.dispose();
    }//GEN-LAST:event_btnCreateAccountUserOKActionPerformed

    private void pwFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwFieldActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void showPasswordChk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordChk1ActionPerformed
        if(showPasswordChk1.isSelected()){
            pwfPW.setEchoChar('\u0000');
            pwfPWconfirm.setEchoChar('\u0000');
        }
        else if (!showPasswordChk1.isSelected()){
            pwfPW.setEchoChar('\u2022');
            pwfPWconfirm.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_showPasswordChk1ActionPerformed

    private void btnCreateAccountUserOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountUserOK1ActionPerformed
        PCreateAccount.dispose();
        PCreateAccountUserC.dispose();
        clear();
    }//GEN-LAST:event_btnCreateAccountUserOK1ActionPerformed


    
    
  






    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LStatus;
    private javax.swing.JLabel Lconfirmpw;
    private javax.swing.JLabel Lpw;
    private javax.swing.JDialog PCreateAccount;
    private javax.swing.JDialog PCreateAccountUser;
    private javax.swing.JDialog PCreateAccountUserC;
    private javax.swing.JButton btnCreateAccountUserOK;
    private javax.swing.JButton btnCreateAccountUserOK1;
    private javax.swing.JButton btnPCAcancel;
    private javax.swing.JButton btnPCAconfirm;
    private javax.swing.JButton cancelBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JPasswordField pwfPW;
    private javax.swing.JPasswordField pwfPWconfirm;
    private javax.swing.JCheckBox showPasswordChk;
    private javax.swing.JCheckBox showPasswordChk1;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JTextField userTf;
    // End of variables declaration//GEN-END:variables
}
